//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SPF_Wpf.ProjectService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProjectService.SPF_WSSoap")]
    public interface SPF_WSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SPF_Wpf.ProjectService.User[] GetUsers(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<SPF_Wpf.ProjectService.User[]> GetUsersAsync(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProjects", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SPF_Wpf.ProjectService.Project[] GetProjects();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetProjects", ReplyAction="*")]
        System.Threading.Tasks.Task<SPF_Wpf.ProjectService.Project[]> GetProjectsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void SaveProject(SPF_Wpf.ProjectService.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveProject", ReplyAction="*")]
        System.Threading.Tasks.Task SaveProjectAsync(SPF_Wpf.ProjectService.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProject", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        void DeleteProject(SPF_Wpf.ProjectService.Project project);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteProject", ReplyAction="*")]
        System.Threading.Tasks.Task DeleteProjectAsync(SPF_Wpf.ProjectService.Project project);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class User : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string emailField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Project : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string abbreviationField;
        
        private string customerField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string abbreviation {
            get {
                return this.abbreviationField;
            }
            set {
                this.abbreviationField = value;
                this.RaisePropertyChanged("abbreviation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string customer {
            get {
                return this.customerField;
            }
            set {
                this.customerField = value;
                this.RaisePropertyChanged("customer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SPF_WSSoapChannel : SPF_Wpf.ProjectService.SPF_WSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SPF_WSSoapClient : System.ServiceModel.ClientBase<SPF_Wpf.ProjectService.SPF_WSSoap>, SPF_Wpf.ProjectService.SPF_WSSoap {
        
        public SPF_WSSoapClient() {
        }
        
        public SPF_WSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SPF_WSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPF_WSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SPF_WSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SPF_Wpf.ProjectService.User[] GetUsers(string email, string password) {
            return base.Channel.GetUsers(email, password);
        }
        
        public System.Threading.Tasks.Task<SPF_Wpf.ProjectService.User[]> GetUsersAsync(string email, string password) {
            return base.Channel.GetUsersAsync(email, password);
        }
        
        public SPF_Wpf.ProjectService.Project[] GetProjects() {
            return base.Channel.GetProjects();
        }
        
        public System.Threading.Tasks.Task<SPF_Wpf.ProjectService.Project[]> GetProjectsAsync() {
            return base.Channel.GetProjectsAsync();
        }
        
        public void SaveProject(SPF_Wpf.ProjectService.Project project) {
            base.Channel.SaveProject(project);
        }
        
        public System.Threading.Tasks.Task SaveProjectAsync(SPF_Wpf.ProjectService.Project project) {
            return base.Channel.SaveProjectAsync(project);
        }
        
        public void DeleteProject(SPF_Wpf.ProjectService.Project project) {
            base.Channel.DeleteProject(project);
        }
        
        public System.Threading.Tasks.Task DeleteProjectAsync(SPF_Wpf.ProjectService.Project project) {
            return base.Channel.DeleteProjectAsync(project);
        }
    }
}
